services:
# TODO: add SRS service (ossrs/srs) for WebRTC transmux
  restreamer:
    image: datarhei/restreamer
    container_name: restreamer
    ports:
      - 1935:1935
      - 8080:8080
    networks:
      - haus-network
    volumes:
      - "~/db:/restreamer/db"
    environment:
      - RS_USERNAME=${RS_USERNAME:-haus}
      - RS_PASSWORD=${RS_PASSWORD:-hauslive}
      - RS_LOGLEVEL=4
      - RS_TIMEZONE=Europe/Berlin
      - RS_SNAPSHOT_INTERVAL=1m

  # TODO: configure domain & SSL
  # https-portal:
  #   image: steveltn/https-portal:1
  #   container_name: https-portal
  #   ports:
  #     - 80:80
  #     - 443:443
  #   restart: always
  #   networks:
  #     - frontend
  #   environment:
  #     DOMAINS: localhost -> http://restreamer:8080
  #     STAGE: local
  #     # DOMAINS: yourdomain.com -> http://restreamer:8080
  #     # STAGE: production

networks:
  haus-network:
